### ISSUE TITLE
There's a lot of warn spam about animation interpolation steps

### ISSUE THREAD

**Issue by janhohenheim** [kaosat-dev/Blender_bevy_components_workflow#139] opened 2024-02-20 22:15 UTC
The animation example and my own code produce the warning "Animation interpolation Step is not supported, will use linear" even though all interpolation steps are linear. AFAIK there are two scenarios where this can happen:
- Animations are exported with optimizations. Does the `bevy_components` do this? If so, it shouldn't.
- An invalid or no animation at all is registered in an animation clip. This can happen if something went wrong during the GLTF export or simply when the first NLA track is empty.

For reference, this is the output of the animations example:
![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/9047632/c6a6d913-5e63-4cb1-8db7-6c44ad7ff129)

**Comment by kaosat-dev** [comment] 2024-02-21 08:54
Hi @janhohenheim !
Yeah that spam is pretty annoying !

Important foreword (not meant to be pedantic, just important)
* ```bevy_components``` does not deal with exporting gltfs, ```gltf_auto_export``` does :)

For the rest:
* Best way to check if the exporter is causing the issue is to export an animated gltf using the standard Blender exporter
* Because of how the standard gltf is structured (ie, non reusable , very complex UI), I only included a stripped down version of the export settings (notably for animation). 

This is also potentially related to #131 and #37.
I have found only one acceptable possible fix for this so far (if it does indeed stem from the exporter):
* force users to use the standard gltf exporter ONCE to setup all gltf related config & store those settings
* in ```gltf_auto_export``` read & use those settings for exporting

Not a huge fan, but most likely the best option short term to have all export settings available.

**Comment by janhohenheim** [comment] 2024-02-21 09:57
Good morning!
Oh yep, you're right, I meant so write `gltf_auto_export` of course 😄
I'm not sure how I can export a single model manually while it continues to play nice with the Blender workflow. If I just naively export my selected model into the `library` dir, I get a `WARN bevy_animation: Animation player on 223v0 did not match any entity paths`. If I don't use the blueprint workflow and only use `bevy_gltf_components`, I have no warnings for the animation. This makes me think that `gltf_auto_export` is using animation optimizations, which need to be disabled when exporting manually to play nice with Bevy:
![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/9047632/adff930f-9e08-4d1f-8407-3b03dce4f4ef)
Note that these are on by default.

**Comment by kaosat-dev** [comment] 2024-02-22 07:58
@janhohenheim Thanks for the invesitgation work :)
Weird thing is, I have also dug ````gltf_auto_export```'s code relevant to what options get passed to Blender's gltf exporter
and the animation optimisation is not present (was supposed to be barebones anyway)

![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/31327a59-75a8-46aa-8769-13aa5037027e)

So I am looking into the Blender's gltf exporter code to see if it is **on** by defaults when calling the exporter from code...

**Comment by kaosat-dev** [comment] 2024-02-22 08:07
yep, bingo! 

![image](https://github.com/kaosat-dev/Blender_bevy_components_workflow/assets/623281/1116aeaf-2178-4c8a-b365-e39ccb48a044)

**Comment by kaosat-dev** [comment] 2024-02-22 08:09
ok so @janhohenheim I have a two tiered solution to propose:
* for now I can just set animation optimisations to False (should at least stop the spam)
* until I reword the UI integration with the default exporter, and then it will be the users's responsibility

**Comment by kaosat-dev** [comment] 2024-02-22 08:10
hmm I also see this one is also on by default:
https://github.com/KhronosGroup/glTF-Blender-IO/blob/949429900a7899efa12323bea4a57ac92b5b68e6/addons/io_scene_gltf2/__init__.py#L649

**Comment by janhohenheim** [comment] 2024-02-22 08:10
@kaosat-dev sounds good! Let me know when there's a branch to try out :)

**Comment by kaosat-dev** [comment] 2024-02-22 08:39
@janhohenheim to make testing even faster (and so you do not need to manually create a zip of the output), here is a zip of the add-on with the change, did a quick test with the animation example, seems to work on my end:

[gltf_auto_export.zip](https://github.com/kaosat-dev/Blender_bevy_components_workflow/files/14371101/gltf_auto_export.zip)

if this works for you , I'll do a quick branch & release (this is independent from the Bevy side anyway)

**Comment by janhohenheim** [comment] 2024-02-22 08:40
@kaosat-dev thanks! I'll be able to test it in the late afternoon

**Comment by janhohenheim** [comment] 2024-02-22 14:39
@kaosat-dev works perfectly now, good job!

**Comment by kaosat-dev** [comment] 2024-02-22 14:46
@janhohenheim , thanks for testing it !
FYI I have a new [PR](https://github.com/kaosat-dev/Blender_bevy_components_workflow/pull/143) in progress, that adds
* this bugfix
* excluding ```components_meta``` (and any invalid, or disable components from ```bevy_components```), so a non stop_gap solution for the components_meta spamming :)
* possibly additional bugfixes
* still need to take that for a spin with the various test files, but should solve a few things

**Closed** 2024-02-26 23:12 UTC
