### ISSUE TITLE
bevy_gltf_components sometimes does not do anything

### ISSUE THREAD

**Issue by janhohenheim** [kaosat-dev/Blender_bevy_components_workflow#111] opened 2024-02-03 17:01 UTC
See Foxtrot at exactly [this commit](https://github.com/janhohenheim/foxtrot/tree/12c321c59b7fdbc1fd778bcce383775e4420b6ab). When starting the game, every now and then (about 1/3), the loading screen stays up forever. Press G to open the `editor_pls` window and you'll see in the hierarchy that no entity has their components that should be inserted by `bevy_gltf_components`.

I hotfixed this by using my own little implementation [here](https://github.com/janhohenheim/foxtrot/blob/c880d2626609d593bf14d63ff3c0417166da8179/src/level_instantiation/spawning.rs#L44-L83) and it works every time.

**Comment by kaosat-dev** [comment] 2024-02-03 22:27
Thanks for the bug report @janhohenheim !
Very weird, I had that issue back in Bevy 0.11, have not had it popup since (then again, I use bevy_gltf_blueprints + bevy_asset_loader usually). I'll investigate.
Btw, I really like your use of querying for ```gltf_extras``` ! 
I have two big PRs coming up for this repo that are almost done, I will take a look at this right afterwards.

**Comment by janhohenheim** [comment] 2024-02-03 22:45
Thanks!

**Comment by kaosat-dev** [comment] 2024-02-03 22:51
Btw one of the PRs drops a lot of the boilerplate present in bevy_gltf_components (soft depreciation, to make it easier for existing users), so I am very tempted to change things up to use your gltf_extras approach as it gets rid of some of the issues of loading scenes vs loading gltf files. 
(When I saw your code I went "d'oh why did I not think of that" 😅)

**Comment by janhohenheim** [comment] 2024-02-04 00:35
hehehe :D Glad to help, I wouldn't have been able to write that if I wasn't able to read your code to begin with. I had no idea how to insert reflect deserialized components!
Btw, a little caveat of the way I deserialize is that the structs in question need to `reflect(Deserialize)`. Do you happen to know if that's because I use a `TypedReflectDeserializer`?

**Comment by kaosat-dev** [comment] 2024-02-04 19:25
Hehe mutually beneficial , open source ftw :)
It has been a long time since I wrote that part, but from what I remember (take this with a pinch of salt or two), I seem to recall I had the same issue , and that is why I moved to ```UntypedReflectDeserializer``` but my brain is in Python / Blender mode today , so no guarantees

**Comment by kaosat-dev** [comment] 2024-02-09 07:30
Hi @janhohenheim !
Just wanted to let you know, I'll experiment in the next few days with a hybrid solution using your idea of "gltf_extras" to see if I can use it as a replacement without breaking the rest (I see no reason why it should not work). I'll ping you once I have something concrete.
I have not been able to reproduce the issue reliably, (I had it pop up once in around 15 tries), but a solution that sidesteps the "load whole gltf" vs "load a scene" issue is an improvement in my book :)

**Comment by janhohenheim** [comment] 2024-02-09 09:12
Sounds good! :) I can also try out change once you've got them on a branch since I can fairly reliably reproduce the issue (1/3 times)

**Comment by kaosat-dev** [comment] 2024-02-18 21:16
Hi @janhohenheim ! Just a short update, finally finished the PR I had going on, so I am switching back to this issue, the use of gltfextras as you did seems completely usable !
I'll fire up a PR tomorrow for you to test out since you have the error reliably :)

**Comment by kaosat-dev** [comment] 2024-02-19 00:14
@janhohenheim , went faster than expected, still wip as I need to double check a few things, but the PR is [here](https://github.com/kaosat-dev/Blender_bevy_components_workflow/pull/134) , would you mind trying it out to see if it solves your issues ?

**Comment by kaosat-dev** [comment] 2024-02-19 17:03
@janhohenheim I think it might be the missing ".git" at the end of the url:
ie , this should work ?
```bevy_gltf_components = { git = "https://github.com/kaosat-dev/Blender_bevy_components_workflow.git", branch = "bevy_gltf_components_gltf_extras" }```

**Comment by kaosat-dev** [comment] 2024-02-19 17:16
hmmm.... @GitGhillie , sorry to tag you, but how where you able to try the branch out ? Thanks !

**Comment by GitGhillie** [comment] 2024-02-19 18:29
No problem! If I can believe the stackoverflow post I saw it should just work but I ran into the same issue :(
So what I did:

1. Clone this repo and switch to the branch
2. Then use path: `bevy_gltf_components = { path = "../Blender_bevy_components_workflow/crates/bevy_gltf_components"}`
3. It will complain about something linting related, so I temporarily removed all the linting stuff from the Cargo.toml in the workspace root and the Cargo.toml of bevy_gltf_components

**Comment by janhohenheim** [comment] 2024-02-19 19:02
@GitGhillie I'll try that then, thanks!
@kaosat-dev sounds like somewhere in the repo some misconfiguration happened :/

**Comment by janhohenheim** [comment] 2024-02-19 19:09
@kaosat-dev found the issue! The lints issue that @GitGhillie ran into is the reason why the crate resolution fails.
Seems like the following is not valid:
```rust
[lints]
workspace = true
```
because after [this commit](https://github.com/janhohenheim/Blender_bevy_components_workflow/commit/bae856b2f34936f9a7af7833671a783e381f4508), my crate resolution works!

**Comment by janhohenheim** [comment] 2024-02-19 19:14
Alright, found the actual mistake, sending a PR

**Comment by kaosat-dev** [comment] 2024-02-19 19:48
Thanks a lot @GitGhillie  & @janhohenheim ! :)
@janhohenheim, I merged your PR onto main & onto the branch for this issue, should be good to go for testing :)

**Comment by janhohenheim** [comment] 2024-02-19 20:52
@kaosat-dev can confirm that the branch in question fixes the bug 🎉 everything loads perfectly every time!

**Comment by kaosat-dev** [comment] 2024-02-19 21:42
Awesome @janhohenheim ! Merging now :)
v0.3.2 of ```bevy_gltf_components``` is also out on crates.io

Thanks a lot for your help, much appreciated :) (added you to the list of contributors)

**Closed** 2024-02-19 21:43 UTC
